// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfCkJhAkNB4VMqhqvh7KUMAKI-jsrxkUU',
    appId: '1:1097572292005:web:817f28de0683bf9008444c',
    messagingSenderId: '1097572292005',
    projectId: 'moodspeak-b6bad',
    authDomain: 'moodspeak-b6bad.firebaseapp.com',
    storageBucket: 'moodspeak-b6bad.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUiTb_6VtRtcbo4Bm9l5Gs9Zxqogu29SA',
    appId: '1:1097572292005:android:6cd7e82eca74a3d308444c',
    messagingSenderId: '1097572292005',
    projectId: 'moodspeak-b6bad',
    storageBucket: 'moodspeak-b6bad.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCfCkJhAkNB4VMqhqvh7KUMAKI-jsrxkUU',
    appId: '1:1097572292005:web:6ec784f5df9e80e008444c',
    messagingSenderId: '1097572292005',
    projectId: 'moodspeak-b6bad',
    authDomain: 'moodspeak-b6bad.firebaseapp.com',
    storageBucket: 'moodspeak-b6bad.firebasestorage.app',
  );

}